FriendBills.MVC/ViewModels/BillViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FriendBills.Presentation.ViewModels
{
    public class BillViewModel
    {
        [Key]
        [ScaffoldColumn(false)]
        public long BillId { get; set; }

        [Required(ErrorMessage = "Preencha o campo Descrição")]
        [MaxLength(100, ErrorMessage = "Máximo de {0} caracteres")]
        [MinLength(2, ErrorMessage = "Mínimo de {0} caracteres")]
        [DisplayName("Descrição")]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Informe a Data")]
        [DisplayFormat(DataFormatString = "{0:dd/mm/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data da conta")]
        public DateTime Date { get; set; }

        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "0", "999999999999")]
        public decimal SubTotal { get; set; }

        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "0", "999999999999")]
        [Required(ErrorMessage = "Informe o valor da conta")]
        public decimal Total { get; set; }

        public bool IsPaid { get; set; }

        [ScaffoldColumn(false)]
        [Required(ErrorMessage = "Selecione o usuário proprietário da conta")]
        public long PersonId { get; set; }

        public virtual PersonViewModel Person { get; set; }

        [ScaffoldColumn(false)]
        public long FriendGroupId { get; set; }

        public virtual FriendGroupViewModel FriendGroup { get; set; }

        [ScaffoldColumn(false)]
        public virtual IEnumerable<PaymentViewModel> Payments { get; set; }

    }
}

FriendBills.MVC/Controllers/BillController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using FriendBills.Application.Interfaces;
using FriendBills.Domain.Entities;
using FriendBills.Presentation.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using FriendBills.Presentation.AutoMapper;
using System;

namespace FriendBills.MVC.Controllers
{
    public class BillController : Controller
    {
        private readonly IBillAppService _billApp;
        private readonly IPersonAppService _personApp;
        private readonly IPaymentAppService _paymentApp;
        private readonly IFriendGroupAppService _groupApp;

        public BillController(IBillAppService billApp, IPersonAppService personApp, IPaymentAppService paymentApp, IFriendGroupAppService groupApp)
        {
            _billApp = billApp;
            _personApp = personApp;
            _paymentApp = paymentApp;
            _groupApp = groupApp;
        }

        // GET: /Bill/
        public IActionResult Index()
        {
            return View(AutoMapperConfig.MapDomainToViewModel<IEnumerable<BillViewModel>, IEnumerable<Bill>>(_billApp.GetAll()));
        }

        // GET: /Bill/
        public IActionResult GetPaidBills()
        {
            return View("Index", AutoMapperConfig.MapDomainToViewModel<IEnumerable<BillViewModel>, IEnumerable<Bill>>(_billApp.GetPaidBills()));
        }

        // GET: /Bill/
        public IActionResult GetNotPaidBills()
        {
            return View("Index", AutoMapperConfig.MapDomainToViewModel<IEnumerable<BillViewModel>, IEnumerable<Bill>>(_billApp.GetNotPaidBills()));
        }

        // GET: /Bill/Details/?
        public IActionResult Details(long id)
        {
            var billViewModel = GetDetailsByBill(id, true);
            billViewModel.Payments = new PaymentController(_billApp, _personApp, _paymentApp, _groupApp).GetPaymentsByBill(id); 
            return View(billViewModel);
        }

        // GET: /Bill/Create
        public IActionResult Create()
        {
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
            ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "FriendGroupId", "Name");

            return View();
        }

        // POST: /Bill/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BillViewModel currentBill)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _billApp.Insert(AutoMapperConfig.MapViewModelToDomain<Bill, BillViewModel>(currentBill));

                    return RedirectToAction("Index");
                }

                ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
                ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "FriendGroupId", "Name");

                return View(currentBill);
            }
            catch
            {
                return View();
            }
        }

        // GET: /Bill/Edit/?
        public IActionResult Edit(long id)
        {
            var billViewModel = GetDetailsByBill(id, true);
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName", billViewModel.PersonId);
            ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "FriendGroupId", "Name", billViewModel.FriendGroupId);

            return View(billViewModel);
        }

        // POST: /Bill/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BillViewModel currentBill)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Payment payment = new Payment();
                        payment.Amount = currentBill.SubTotal;

                    Bill billToUpdate = _paymentApp.UpdadeIfPaid(payment, AutoMapperConfig.MapViewModelToDomain<Bill, BillViewModel>(currentBill));
                    _billApp.Update(billToUpdate);

                    return RedirectToAction("Index");
                }

                ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName", currentBill.PersonId);
                ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "GroupId", "Name", currentBill.FriendGroupId);

                return View(currentBill);
            }
            catch
            {
                return View();
            }     
        }

        // GET: /Bill/Delete/?
        public IActionResult Delete(long id)
        {
            var billViewModel = GetDetailsByBill(id, true);

            return View(billViewModel);
        }

        // POST: /Bill/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            try
            {
                _personApp.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public BillViewModel GetDetailsByBill(long id, bool tracking)
        {
            Bill bill = new Bill();
            if(tracking)
            {
                bill = _billApp.GetById(id);
            }
            else
            {
                bill = _billApp.GetByIdNoTracking(id);
            }
            return AutoMapperConfig.MapDomainToViewModel<BillViewModel, Bill>(bill);
        }
    }
}

FriendBills.MVC/Controllers/PaymentController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FriendBills.Presentation.ViewModels;
using FriendBills.Domain.Entities;
using FriendBills.Application.Interfaces;
using FriendBills.Presentation.AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace FriendBills.MVC.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPaymentAppService _paymentApp;
        private readonly IBillAppService _billApp;
        private readonly IPersonAppService _personApp;
        private readonly IFriendGroupAppService _groupApp;

        public PaymentController(IBillAppService billApp, IPersonAppService personApp, IPaymentAppService paymentApp, IFriendGroupAppService groupApp)
        {
            _billApp = billApp;
            _personApp = personApp;
            _paymentApp = paymentApp;
            _groupApp = groupApp;
        }

        // GET: Payment
        public IActionResult Index()
        {
            return View(AutoMapperConfig.MapDomainToViewModel<IEnumerable<PaymentViewModel>, IEnumerable<Payment>>(_paymentApp.GetAll()));
        }

        // GET: Payment/Teste
        public IActionResult Create(long id)
        {
            ViewBag.BillId = new SelectList(_billApp.GetNotPaidBills(), "BillId", "Description", id);
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
            ViewBag.BillId_Detail = id;
            return View();
        }

        // POST: Payment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PaymentViewModel currentPayment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    BillController bc = new BillController(_billApp, _personApp, _paymentApp, _groupApp);

                    _paymentApp.Insert(AutoMapperConfig.MapViewModelToDomain<Payment, PaymentViewModel>(currentPayment));

                    Bill billToUpdate = _paymentApp.UpdateBillSubtotal(
                        AutoMapperConfig.MapViewModelToDomain<Payment, PaymentViewModel>(currentPayment), 
                        AutoMapperConfig.MapViewModelToDomain<Bill, BillViewModel>(bc.GetDetailsByBill(currentPayment.BillId, false)));

                    billToUpdate = _paymentApp.UpdadeIfPaid(AutoMapperConfig.MapViewModelToDomain<Payment, PaymentViewModel>(currentPayment), billToUpdate);

                    _billApp.Update(billToUpdate);
                }

                ViewBag.BillId = new SelectList(_billApp.GetNotPaidBills(), "BillId", "Description", currentPayment.BillId);
                ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");

                return RedirectToAction("Details", "Bill", new { id = currentPayment.BillId });
            }
            catch
            {
                return View();
            }
        }

        // GET: Payment/Delete/5
        public IActionResult Delete(int id)
        {
            return View();
        }

        // POST: Payment/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public IEnumerable<PaymentViewModel> GetPaymentsByBill(long id)
        {
            return AutoMapperConfig.MapDomainToViewModel<IEnumerable<PaymentViewModel>, IEnumerable<Payment>>(_paymentApp.GetPaymentsByBill(id));
        }

    }
}

FriendBills.MVC/Views/Bill/Create.cshtml
@model FriendBills.Presentation.ViewModels.BillViewModel

@{
    ViewData["Title"] = "Cadastrar";
}

<h2>Cadastrar</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Conta entre amigos</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Date" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Total" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PersonId" class="col-md-2 control-label">Usuário criador</label>
            <div class="col-md-10">
                @Html.DropDownList("PersonId", "--Selecione--")
                @Html.ValidationMessageFor(model => model.PersonId, "", new {  @class = "text-danger"  })
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FriendGroupId" class="col-md-2 control-label">Grupo de amigos</label>
            <div class="col-md-10">
                @Html.DropDownList("FriendGroupId", "--Selecione--")
                @Html.ValidationMessageFor(model => model.FriendGroupId, "", new { @class = "text-danger" })
                <span asp-validation-for="FriendGroupId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendBills.MVC/Views/Bill/Delete.cshtml
@model FriendBills.Presentation.ViewModels.BillViewModel

@{
    ViewData["Title"] = "Excluir";
}

<h2>Excluir</h2>

<h3>Tem certeza que deseja deletar esta conta?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayName("Quitada?")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        @Html.HiddenFor(model => model.BillId)
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            <a asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

FriendBills.MVC/Views/Bill/Details.cshtml
@model FriendBills.Presentation.ViewModels.BillViewModel

@{
    ViewData["Title"] = "Detalhe";
}

<h2>Detalhe</h2>
<p>
    @if (Model.IsPaid == false)
    {
        <a asp-action="Index">Voltar |</a>
        @Html.ActionLink("Editar", "Edit", new { id = Model.BillId }) @:|
        @Html.ActionLink("Registrar pagamento", "Create", "Payment", new { id = Model.BillId })
    }
    else
    {
        <a asp-action="Index">Voltar</a>
    }
</p>

<div>
    <h4>Conta entre amigos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayName("Quitada?")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        <dt>
        @Html.DisplayName("Usuário")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Person.NickName)
        </dd>
        <dt>
            @Html.DisplayName("Grupo de amigos")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FriendGroup.Name)
        </dd>
    </dl>
</div>
<div>
    <br />
    <h4>Dados de pagamentos realizados</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Pagante")
                </th>
                <th>
                    @Html.DisplayName("Valor")
                </th>
                <th>
                    @Html.DisplayName("Data")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Payments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.LastName), @Html.DisplayFor(modelItem => item.Person.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FriendBills.MVC/Views/Bill/Edit.cshtml
@model FriendBills.Presentation.ViewModels.BillViewModel

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Conta entre amigos</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Total" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PersonId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @Html.DropDownList("PersonId", (SelectList)ViewBag.PersonId, "--Selecione--")
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FriendGroupId" class="col-md-2 control-label">Grupo de amigos</label>
            <div class="col-md-10">
                @Html.DropDownList("FriendGroupId", (SelectList)ViewBag.FriendGroupId, "--Selecione--")
                @Html.ValidationMessageFor(model => model.FriendGroupId, "", new { @class = "text-danger" })
                <span asp-validation-for="FriendGroupId" class="text-danger"></span>
            </div>
        </div>

        <input asp-for="BillId" type="hidden" />
        <input asp-for="Date" type="hidden" />
        <input asp-for="SubTotal" type="hidden" />
        <input asp-for="IsPaid" type="hidden" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendBills.MVC/Views/Bill/Index.cshtml
@model IEnumerable<FriendBills.Presentation.ViewModels.BillViewModel>

@{
    ViewData["Title"] = "Lista de Contas";
}

<h2>Lista de Contas</h2>

<p>
    <a asp-action="Create">Cadastrar nova</a>
</p>
<p>
    Filtro de contas:
    <a asp-action="Index">todas</a>
     | 
    <a asp-action="GetPaidBills">pagas</a>
     | 
    <a asp-action="GetNotPaidBills">em aberto</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubTotal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th>
                    @Html.DisplayName("Quitada?")
                </th>
                <th>
                    @Html.DisplayName("Usuário")
                </th>
            <th>
                @Html.DisplayName("Grupo de amigos")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Person.NickName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FriendGroup.Name)
            </td>
            <td>
                @if (item.IsPaid == false) { 
                    @Html.ActionLink("Editar", "Edit", new { id = item.BillId }) @:|
                    @Html.ActionLink("Detalhes", "Details", new { id = item.BillId }) @:|
                    @Html.ActionLink("Excluir", "Delete", new { id = item.BillId });
                }
                else
                {
                    @Html.ActionLink("Detalhes", "Details", new { id = item.BillId })
                }
            </td>
        </tr>
}
    </tbody>
</table>