FriendBills.MVC/Controllers/GroupController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using FriendBills.Application.Interfaces;
using FriendBills.Presentation.AutoMapper;
using FriendBills.Presentation.ViewModels;
using FriendBills.Domain.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FriendBills.MVC.Controllers
{
    public class GroupController : Controller
    {
        private readonly IFriendGroupAppService _groupApp;
        private readonly IPersonAppService _personApp;
        private readonly IPersonGroupAppService _personGroupApp;


        public GroupController(IFriendGroupAppService groupApp, IPersonAppService personApp, IPersonGroupAppService personGroup)
        {
            _groupApp = groupApp;
            _personApp = personApp;
            _personGroupApp = personGroup;
        }

        // GET: Group
        public IActionResult Index()
        {
            return View(AutoMapperConfig.MapDomainToViewModel<IEnumerable<FriendGroupViewModel>, IEnumerable<FriendGroup>>(_groupApp.GetAll()));
        }

        // GET: Group/Details/5
        public IActionResult Details(long id)
        {
            var groupViewModel = GetDetailsByGroup(id);
            groupViewModel.PersonsGroup = new PersonGroupController(_personGroupApp, _personApp,  _groupApp).GetPersonsByGroup(id);

            return View(groupViewModel);
        }

        // GET: Group/Create
        public IActionResult Create()
        {
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
            return View();
        }

        // POST: Group/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FriendGroupViewModel currentGroup)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _groupApp.Insert(AutoMapperConfig.MapViewModelToDomain<FriendGroup, FriendGroupViewModel>(currentGroup));

                    return RedirectToAction("Index");
                }

                ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");

                return View(currentGroup);
            }
            catch
            {
                return View();
            }
        }

        // GET: Group/Edit/5
        public IActionResult Edit(long id)
        {
            var groupViewModel = GetDetailsByGroup(id);
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName", groupViewModel.PersonId);

            return View(groupViewModel);
        }

        // POST: Group/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FriendGroupViewModel currentGroup)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _groupApp.Update(AutoMapperConfig.MapViewModelToDomain<FriendGroup, FriendGroupViewModel>(currentGroup));

                    return RedirectToAction("Index");
                }

                return View(currentGroup);
            }
            catch
            {
                return View();
            }
        }

        // GET: Group/Delete/5
        public IActionResult Delete(long id)
        {
            var groupViewModel = GetDetailsByGroup(id);

            return View(groupViewModel);
        }

        // POST: Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            try
            {
                _groupApp.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //private methods
        private FriendGroupViewModel GetDetailsByGroup(long id)
        {
            var group = _groupApp.GetById(id);
            return AutoMapperConfig.MapDomainToViewModel<FriendGroupViewModel, FriendGroup>(group);
        }
    }
}

FriendBills.MVC/Controllers/PersonGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FriendBills.Application.Interfaces;
using FriendBills.Presentation.ViewModels;
using FriendBills.Domain.Entities;
using FriendBills.Presentation.AutoMapper;

namespace FriendBills.MVC.Controllers
{
    public class PersonGroupController : Controller
    {
        private readonly IPersonGroupAppService _personGroupApp;
        private readonly IPersonAppService _personApp;
        private readonly IFriendGroupAppService _groupApp;
        
        public PersonGroupController(IPersonGroupAppService personGroupApp, IPersonAppService personApp, IFriendGroupAppService groupApp)
        {
            _personGroupApp = personGroupApp;
            _personApp = personApp;
            _groupApp = groupApp;
        }


        // GET: PersonGroup
        public IActionResult Index()
        {
            return View(AutoMapperConfig.MapDomainToViewModel<IEnumerable<PersonGroupViewModel>, IEnumerable<PersonGroup>>(_personGroupApp.GetAll()));
        }

        // GET: PersonGroup/Create
        public IActionResult Create(long id)
        {
            ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "FriendGroupId", "Name", id);
            ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
            ViewBag.GroupId_Detail = id;

            return View();
        }

        // POST: PersonGroup/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PersonGroupViewModel currentPersonGroup)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _personGroupApp.Insert(AutoMapperConfig.MapViewModelToDomain<PersonGroup, PersonGroupViewModel>(currentPersonGroup));
                }

                ViewBag.PersonId = new SelectList(_personApp.GetActivePersons(), "PersonId", "NickName");
                ViewBag.FriendGroupId = new SelectList(_groupApp.GetAll(), "FriendGroupId", "Name");

                return RedirectToAction("Details", "Group", new { id = currentPersonGroup.FriendGroupId } );
            }
            catch
            {
                return View();
            }
        }

        
        // GET: PersonGroup/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PersonGroup/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public IEnumerable<PersonGroupViewModel> GetPersonsByGroup(long id)
        {
            return AutoMapperConfig.MapDomainToViewModel<IEnumerable<PersonGroupViewModel>, IEnumerable<PersonGroup>>(_personGroupApp.GetPersonsByGroup(id));
        }
    }
}

FriendBills.MVC/Views/Group/Create.cshtml
@model FriendBills.Presentation.ViewModels.FriendGroupViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Cadastrar</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Grupo de amigos</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Person" class="col-md-2 control-label">Dono do Grupo</label>
            <div class="col-md-10">
                @Html.DropDownList("PersonId", "--Selecione--")
                @Html.ValidationMessageFor(model => model.Person.PersonId, "", new { @class = "text-danger" })
                <span asp-validation-for="Person" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendBills.MVC/Views/Group/Delete.cshtml
@model FriendBills.Presentation.ViewModels.FriendGroupViewModel

@{
    ViewData["Title"] = "Excluir";
}

<h2>Excluir</h2>

<h3>Tem certeza que deseja deletar este grupo?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
            @Html.HiddenFor(model => model.FriendGroupId)
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            <a asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

FriendBills.MVC/Views/Group/Details.cshtml
@model FriendBills.Presentation.ViewModels.FriendGroupViewModel

@{
    ViewData["Title"] = "Detalhe";
}

<h2>Detalhe</h2>
<p>
        <a asp-action="Index">Voltar |</a>
        @Html.ActionLink("Editar", "Edit", new { id = Model.FriendGroupId }) |
        @Html.ActionLink("Adicionar Pessoa", "Create", "PersonGroup", new { id = Model.FriendGroupId })
</p>
<div>
    <h4>Grupo de amigos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nome do grupo")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
                @Html.DisplayName("Criador")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Person.LastName), @Html.DisplayFor(model => model.Person.FirstName)
            </dd>
        </dl>
    </div>
<div>
    <br />
    <h4>Usuários neste grupo</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Nome")
                </th>
                <th>
                    @Html.DisplayName("Sobrenome")
                </th>
                <th>
                    @Html.DisplayName("Apelido")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PersonsGroup)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.LastName),
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.NickName)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FriendBills.MVC/Views/Group/Edit.cshtml
@model FriendBills.Presentation.ViewModels.FriendGroupViewModel

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Grupo de amigos</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Nome do Grupo</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Person" class="col-md-2 control-label">Criador</label>
            <div class="col-md-10">
                @Html.DropDownList("PersonId", (SelectList)ViewBag.PersonId, "--Selecione--")
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
        <input asp-for="FriendGroupId" type="hidden" />
    </div>
</form>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendBills.MVC/Views/Group/Index.cshtml
@model IEnumerable<FriendBills.Presentation.ViewModels.FriendGroupViewModel>

@{
    ViewData["Title"] = "Lista de Grupos";
}

<h2>Lista de Grupos</h2>

<p>
    <a asp-action="Create">Cadastrar novo</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayName("Nome do Grupo")
                </th>
                <th>
                    @Html.DisplayName("Criador")
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Person.LastName), @Html.DisplayFor(modelItem => item.Person.FirstName)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {  id = item.FriendGroupId }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.FriendGroupId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.FriendGroupId })
            </td>
        </tr>
}
    </tbody>
</table>